language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
 - composer install --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c travis.phpunit.xml

after_script:
  - php vendor/bin/coveralls
  # or enable logging
  #- php vendor/bin/coveralls -v